version: '3'
services:
  jenkins:
    container_name: jenkins
    build:
      context: .
    ports: 
      - "8081:8080"
    volumes:
      - /home/usuario/jenkins/jenkins_home/:/var/jenkins_home
      - /var/run/docker-socker.socker:/var/run/docker.socker